package com.serviceNow.entities;

import com.serviceNow.drivers.SnEntity;

public class SnAlmAsset extends SnEntity
{
  public String acquisition_method;
  public String asset_tag;
  public String assigned;
  //public SnLinkValue assigned_to;
  public String beneficiary;
  public String checked_in;
  public String checked_out;
  //public SnLinkValue ci;
  public String comments;
  //public SnLinkValue company;
  public String cost;
  //public SnLinkValue cost_center;
  public String delivery_date;
  //public SnLinkValue department;
  public String depreciated_amount;
  //public SnLinkValue depreciation;
  public String depreciation_date;
  public String display_name;
  public String disposal_reason;
  public String due;
  public String due_in;
  public String expenditure_type;
  public String gl_account;
  public String install_date;
  public String install_status;
  public String invoice_number;
  public String justification;
  public String lease_id;
  //public SnLinkValue location;
  //public SnLinkValue managed_by;
  //public SnLinkValue model;
  //public SnLinkValue model_category;
  public String old_status;
  public String old_substatus;
  public String order_date;
  //public SnLinkValue owned_by;
  //public SnLinkValue parent;
  public String po_number;
  public String pre_allocated;
  public String purchase_date;
  public String quantity;
  public String request_line;
  public String resale_price;
  public String reserved_for;
  public String residual;
  public String residual_date;
  public String retired;
  public String retirement_date;
  public String salvage_value;
  public String serial_number;
  public String skip_sync;
  //public SnLinkValue stockroom;
  public String substatus;
  //public SnLinkValue support_group;
  //public SnLinkValue supported_by;
  public String sys_class_name;
  public String sys_created_by;
  public String sys_created_on;
  //public SnLinkValue sys_domain;
  public String sys_domain_path;
  public String sys_id;
  public String sys_mod_count;
  public String sys_tags;
  public String sys_updated_by;
  public String sys_updated_on;
  //public SnLinkValue vendor;
  public String warranty_expiration;
  public String work_notes;
}