package com.serviceNow.entities;

import com.serviceNow.drivers.SnEntity;

public class SnAstContract extends SnEntity
{
  public String active;
  public String applicable_taxes;
  public String application_model;
  public String approval_history;
  //public SnLinkValue approver;
  public String business_owner;
  public String commitment;
  //public SnLinkValue contract_administrator;
  //public SnLinkValue contract_model;
  public String cost_adjustment;
  public String cost_adjustment_percentage;
  public String cost_adjustment_reason;
  public String cost_adjustment_type;
  public String cost_center;
  public String cost_per_unit;
  public String covers;
  public String customer;
  public String description;
  public String discount;
  public String ends;
  //public SnLinkValue expiration;
  public String invoice_payment_terms;
  public String license_quantity_entitled;
  public String license_type;
  public String lifetime_cost;
  public String location;
  public String monthly_cost;
  public String number;
  public String parent_contract;
  public String payment_amount;
  public String payment_schedule;
  public String po_number;
  public String process;
  public String process_non_contractual_slas;
  public String ratecard;
  public String renewable;
  public String renewal_contact;
  public String renewal_date;
  public String renewal_end_date;
  public String renewal_options;
  public String sales_tax;
  public String short_description;
  public String starts;
  public String state;
  public String sub_total_cost;
  public String substate;
  public String sys_class_name;
  public String sys_created_by;
  public String sys_created_on;
  //public SnLinkValue sys_domain;
  public String sys_domain_path;
  public String sys_id;
  public String sys_mod_count;
  public String sys_tags;
  public String sys_updated_by;
  public String sys_updated_on;
  public String tax_cost;
  public String tax_exempt;
  public String tax_rate;
  public String terms_and_conditions;
  public String total_cost;
  //public SnLinkValue vendor;
  public String vendor_account;
  public String vendor_contract;
  public String yearly_cost;
}